name: build-executables

on:
  workflow_dispatch
  # pull_request:
  # push:
  #   branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          EXECUTABLE_DIR="dist/ollama-chatbot-${{ runner.os }}"
          mkdir -p "$EXECUTABLE_DIR"
          pyinstaller --onedir --name "Ollama Chatbot" --windowed chatbot/ollama_chatbot.py
          mv dist/"Ollama Chatbot" "$EXECUTABLE_DIR"
        shell: bash

      - name: Create ZIP Archive
        run: |
          case ${{ runner.os }} in
            Linux|macOS)
              zip -r "ollama-chatbot-${{ runner.os }}.zip" "dist/ollama-chatbot-${{ runner.os }}/"
              ;;
            Windows)
              Compress-Archive -Path "dist\ollama-chatbot-Windows\*" -DestinationPath "ollama-chatbot-Windows.zip"
              ;;
            *)
              echo "Unsupported OS: ${{ runner.os }}"
              exit 1
              ;;
          esac

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ollama-chatbot-${{ runner.os }}
          path: ollama-chatbot-${{ runner.os }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bump version and create tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          default_bump: minor
          initial_version: "0.1.0"
          tag_prefix: "v"

      - name: Fetch new tag
        run: git fetch --tags

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
